version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  reviewers:
    - hiago dos santos
  assignees:
    - hiago dos santos
  labels:
    - dependencies
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
